// src/lib/EmailLink.svelte
<script lang="ts">
	import { faEnvelope } from '@fortawesome/free-solid-svg-icons';

	import FontAwesomeIcon from './FontAwesomeIcon.svelte';
</script>

<a tabIndex="0" class="icon-link" role="button" aria-label="Click to see my email">
	<FontAwesomeIcon icon={faEnvelope} />
	<span>Email</span>
</a>

<style lang="scss">
	.icon-link {
		display: flex;
		flex-direction: column;
		align-items: center;
		text-decoration: underline;
	}
</style>

// components/EmailLink.tsx
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";

import homeStyles from "../styles/Home.module.css";
import { EmailDialog } from "./EmailDialog";

export function EmailLink() {
  const [showEmailDialog, setShowEmailDialog] = useState(false);

  return (
    <>
      <a
        tabIndex={0}
        className={homeStyles.iconLink}
        role="button"
        aria-label="Click to see my email"
        onClick={() => setShowEmailDialog(true)}
        onKeyDown={(event) => {
          const { key } = event;
          if (key === "Enter" || key === "Space") {
            event.preventDefault();
            setShowEmailDialog(true);
          }
        }}
      >
        <FontAwesomeIcon icon={faEnvelope} className={homeStyles.icon} />
        <span>Email</span>
      </a>
      <EmailDialog
        isOpen={showEmailDialog}
        onClose={() => setShowEmailDialog(false)}
      />
    </>
  );
}
